ucsb-cs156-s25/team02-s25-10

src/main/java/edu/ucsb/cs156/example/controllers/MenuItemReviewsController.java, src/main/java/edu/ucsb/cs156/example/entities/MenuItemReview.java, src/main/java/edu/ucsb/cs156/example/repositories/MenuItemReviewRepository.java, src/main/resources/db/migration/changes/MenuItemReviews.json, src/test/java/edu/ucsb/cs156/example/controllers/MenuItemReviewsControllerTests.java
closes #35 
In this PR we copy over the entire CRUD functionality for the reviews table from team01.
=> mh - copied backend CRUD operations from team01 for the reviews table

frontend/package-lock.json, frontend/package.json, frontend/src/fixtures/reviewFixtures.js, src/main/java/edu/ucsb/cs156/example/controllers/MenuItemReviewsController.java, src/main/java/edu/ucsb/cs156/example/entities/MenuItemReview.java, src/main/java/edu/ucsb/cs156/example/repositories/MenuItemReviewRepository.java, src/main/resources/db/migration/changes/MenuItemReviews.json, src/test/java/edu/ucsb/cs156/example/controllers/MenuItemReviewsControllerTests.java
closes #36 
In this PR we added fixtures for the MenuItemReviews.
=> Mh review fixtures

src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationsController.java, src/main/java/edu/ucsb/cs156/example/entities/UCSBOrganization.java, src/main/java/edu/ucsb/cs156/example/repositories/UCSBOrganizationRepository.java, src/main/resources/db/migration/changes/UCSBOrganization.json, src/test/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationsControllerTests.java
Closes #17 
Copying files from team01
=> bs - Copy files for Backend CRUD API MenuItemReview from team02

frontend/src/fixtures/ucsbOrganizationFixtures.js
Closes #18 
MERGE AFTER PR #62 
In this PR, we add fixtures for the commit table in the frontend code. 
These will be used for tests and storybook entries later on.
=> bs - create fixtures for commit table

src/main/java/edu/ucsb/cs156/example/controllers/RecommendationRequestsController.java, src/main/java/edu/ucsb/cs156/example/entities/RecommendationRequest.java, src/main/java/edu/ucsb/cs156/example/repositories/RecommendationRequestRepository.java, src/main/resources/db/migration/changes/RecommendationRequests.json, src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestsControllerTests.java
Closes #26 
In this PR, I added the CRUD API actions from RecommendationRequests.
=> mk - copy backend CRUD operations

frontend/src/fixtures/helpRequestsFixtures.js, src/main/java/edu/ucsb/cs156/example/controllers/HelpRequestsController.java, src/main/java/edu/ucsb/cs156/example/entities/HelpRequest.java, src/main/java/edu/ucsb/cs156/example/repositories/HelpRequestRepository.java, src/main/resources/db/migration/changes/HelpRequests.json, src/test/java/edu/ucsb/cs156/example/controllers/HelpRequestsControllerTests.java
closes #45 
Merge after PR #69 (this branch is base on that branch)
In this PR, we add fixtures for the help requests table in the frontend code.
This will be used for the storybook tests.
=> Mz - helprequests javscript fixtures

frontend/src/fixtures/recommendationRequestFixtures.js, frontend/src/main/components/RecommendationRequests/RecommendationForm.js, frontend/src/stories/components/RecommendationRequests/RecommendationForm.stories.js, frontend/src/tests/components/RecommendationRequests/RecommendationForm.test.js, src/main/java/edu/ucsb/cs156/example/controllers/RecommendationRequestsController.java, src/main/java/edu/ucsb/cs156/example/entities/RecommendationRequest.java, src/main/java/edu/ucsb/cs156/example/repositories/RecommendationRequestRepository.java, src/main/resources/db/migration/changes/RecommendationRequests.json, src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestsControllerTests.java
Closes #28 
This is a replacement for the previous PR, it adds testing for Storybook and fixes the formatting.
=> Mk recrequest formtests

frontend/src/fixtures/recommendationRequestFixtures.js, frontend/src/main/components/RecommendationRequests/RecommendationForm.js, frontend/src/stories/components/RecommendationRequests/RecommendationForm.stories.js, src/main/java/edu/ucsb/cs156/example/controllers/RecommendationRequestsController.java, src/main/java/edu/ucsb/cs156/example/entities/RecommendationRequest.java, src/main/java/edu/ucsb/cs156/example/repositories/RecommendationRequestRepository.java, src/main/resources/db/migration/changes/RecommendationRequests.json, src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestsControllerTests.java
Closes #28 
Finished integrating recommendations request with the storybook.
=> Mk recrequest form

frontend/package-lock.json, frontend/src/fixtures/recommendationRequestFixtures.js, frontend/src/main/components/RecommendationRequests/RecommendationForm.js, frontend/src/main/components/RecommendationRequests/RecommendationTable.js, frontend/src/main/utils/recommendationRequestUtils.js, frontend/src/stories/components/RecommendationRequests/RecommendationForm.stories.js, frontend/src/stories/components/RecommendationRequests/RecommendationTable.stories.js, frontend/src/tests/components/RecommendationRequests/RecommendationForm.test.js, frontend/src/tests/components/RecommendationRequests/RecommendationTable.test.js, frontend/src/tests/utils/recommendationRequestUtils.test.js, src/main/java/edu/ucsb/cs156/example/controllers/RecommendationRequestsController.java, src/main/java/edu/ucsb/cs156/example/entities/RecommendationRequest.java, src/main/java/edu/ucsb/cs156/example/repositories/RecommendationRequestRepository.java, src/main/resources/db/migration/changes/RecommendationRequests.json, src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestsControllerTests.java
Closes #29 
Adds table for recommendation requests.
TODO: Insert Storybook link
TODO: Insert screenshot of table
=> Mk recrequest table

frontend/src/fixtures/UCSBDiningCommonsMenuItemFixtures.js, src/main/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemController.java, src/main/java/edu/ucsb/cs156/example/entities/UCSBDiningCommonsMenuItem.java, src/main/java/edu/ucsb/cs156/example/repositories/UCSBDiningCommonsMenuItemRepository.java, src/main/resources/db/migration/changes/UCSBDiningCommonsMenuItems.json, src/test/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemControllerTests.java
Closes #9 
In this PR, we added fixtures for UCSBDiningCommonsMenuItem
will be used for tests and storybook entries later on.
=> Ac create ucsb dining commons menu item fixtures

frontend/src/fixtures/UCSBDiningCommonsMenuItemFixtures.js, frontend/src/main/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemForm.js, frontend/src/stories/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemForm.stories.js, frontend/src/tests/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemForm.test.js, src/main/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemController.java, src/main/java/edu/ucsb/cs156/example/entities/UCSBDiningCommonsMenuItem.java, src/main/java/edu/ucsb/cs156/example/repositories/UCSBDiningCommonsMenuItemRepository.java, src/main/resources/db/migration/changes/UCSBDiningCommonsMenuItems.json, src/test/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemControllerTests.java
In this PR, we created the component for UCSBDiningCommonsMenuItemForm.
We only added to storybook, not the frontend yet.
Closes #10
=> Ac ucsb dining commons menu item components

frontend/src/fixtures/UCSBDiningCommonsMenuItemFixtures.js, frontend/src/main/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemForm.js, frontend/src/main/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemTable.js, frontend/src/main/utils/UCSBDiningCommonsMenuItemUtils.js, frontend/src/stories/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemForm.stories.js, frontend/src/stories/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemTable.stories.js, frontend/src/tests/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemForm.test.js, frontend/src/tests/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemTable.test.js, frontend/src/tests/utils/UCSBDiningCommonsMenuItemUtils.test.js, src/main/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemController.java, src/main/java/edu/ucsb/cs156/example/entities/UCSBDiningCommonsMenuItem.java, src/main/java/edu/ucsb/cs156/example/repositories/UCSBDiningCommonsMenuItemRepository.java, src/main/resources/db/migration/changes/UCSBDiningCommonsMenuItems.json, src/test/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemControllerTests.java
Closes #11 
In this PR, we added UCSBDiningCommonsMenuItem Table
=> Ac ucsb dining commons menu item table

frontend/package-lock.json, frontend/package.json, frontend/src/fixtures/reviewFixtures.js, frontend/src/main/components/MenuItemReviews/ReviewForm.js, frontend/src/main/components/MenuItemReviews/ReviewTable.js, frontend/src/main/utils/reviewUtils.js, frontend/src/stories/components/MenuItemReviews/ReviewForm.stories.js, frontend/src/stories/components/MenuItemReviews/ReviewTable.stories.js, frontend/src/tests/components/MenuItemReviews/ReviewForm.test.js, frontend/src/tests/components/MenuItemReviews/ReviewTable.test.js, frontend/src/tests/utils/reviewUtils.test.js, src/main/java/edu/ucsb/cs156/example/controllers/MenuItemReviewsController.java, src/main/java/edu/ucsb/cs156/example/entities/MenuItemReview.java, src/main/java/edu/ucsb/cs156/example/repositories/MenuItemReviewRepository.java, src/main/resources/db/migration/changes/MenuItemReviews.json, src/test/java/edu/ucsb/cs156/example/controllers/MenuItemReviewsControllerTests.java
closes #38 
Added the review table
https://6811b5ebd2e9f3288ae27ed4-ouyywfhtvi.chromatic.com/?path=/story/components-menuitemreviews-reviewform--create
=> Mh review table

frontend/package-lock.json, frontend/src/App.js, frontend/src/fixtures/UCSBDiningCommonsMenuItemFixtures.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemForm.js, frontend/src/main/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemTable.js, frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.js, frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.js, frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.js, frontend/src/main/utils/UCSBDiningCommonsMenuItemUtils.js, frontend/src/stories/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemForm.stories.js, frontend/src/stories/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemTable.stories.js, frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.stories.js, frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.stories.js, frontend/src/tests/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemForm.test.js, frontend/src/tests/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemTable.test.js, frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.test.js, frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.test.js, frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.test.js, frontend/src/tests/utils/UCSBDiningCommonsMenuItemUtils.test.js, src/main/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemController.java, src/main/java/edu/ucsb/cs156/example/entities/UCSBDiningCommonsMenuItem.java, src/main/java/edu/ucsb/cs156/example/repositories/UCSBDiningCommonsMenuItemRepository.java, src/main/resources/db/migration/changes/UCSBDiningCommonsMenuItems.json, src/test/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemControllerTests.java
Closes #14 
In this PR, we add the UCSBDiningCommonsMenuItemIndexPage with stories and tests.
=> Ac ucsb dining commons menu item index page

frontend/package-lock.json, frontend/src/App.js, frontend/src/fixtures/UCSBDiningCommonsMenuItemFixtures.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemForm.js, frontend/src/main/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemTable.js, frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.js, frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.js, frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.js, frontend/src/main/utils/UCSBDiningCommonsMenuItemUtils.js, frontend/src/stories/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemForm.stories.js, frontend/src/stories/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemTable.stories.js, frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.stories.js, frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.stories.js, frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.stories.js, frontend/src/tests/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemForm.test.js, frontend/src/tests/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemTable.test.js, frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.test.js, frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.test.js, frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.test.js, frontend/src/tests/utils/UCSBDiningCommonsMenuItemUtils.test.js, src/main/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemController.java, src/main/java/edu/ucsb/cs156/example/entities/UCSBDiningCommonsMenuItem.java, src/main/java/edu/ucsb/cs156/example/repositories/UCSBDiningCommonsMenuItemRepository.java, src/main/resources/db/migration/changes/UCSBDiningCommonsMenuItems.json, src/test/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemControllerTests.java
Closes #15 
In this PR, we created the UCSBDiningCommonsMenuItemEditPage with tests and story.
=> Ac ucsb dining commons menu item edit page

frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/fixtures/reviewFixtures.js, frontend/src/main/components/MenuItemReviews/ReviewForm.js, frontend/src/main/components/MenuItemReviews/ReviewTable.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/pages/MenuItemReviews/MenuItemReviewCreatePage.js, frontend/src/main/pages/MenuItemReviews/MenuItemReviewEditPage.js, frontend/src/main/pages/MenuItemReviews/MenuItemReviewIndexPage.js, frontend/src/main/utils/reviewUtils.js, frontend/src/stories/components/MenuItemReviews/ReviewForm.stories.js, frontend/src/stories/components/MenuItemReviews/ReviewTable.stories.js, frontend/src/tests/components/MenuItemReviews/ReviewForm.test.js, frontend/src/tests/components/MenuItemReviews/ReviewTable.test.js, frontend/src/tests/pages/MenuItemReviews/MenuItemReviewCreatePage.test.js, frontend/src/tests/pages/MenuItemReviews/MenuItemReviewEditPage.test.js, frontend/src/tests/pages/MenuItemReviews/MenuItemReviewIndexPage.test.js, frontend/src/tests/utils/reviewUtils.test.js, src/main/java/edu/ucsb/cs156/example/controllers/MenuItemReviewsController.java, src/main/java/edu/ucsb/cs156/example/entities/MenuItemReview.java, src/main/java/edu/ucsb/cs156/example/repositories/MenuItemReviewRepository.java, src/main/resources/db/migration/changes/MenuItemReviews.json, src/test/java/edu/ucsb/cs156/example/controllers/MenuItemReviewsControllerTests.java
closes #39 
Created placeholders of the index, edit, and create pages for menu item reviews.
=> Mh review placeholderpages

frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/fixtures/reviewFixtures.js, frontend/src/main/components/MenuItemReviews/ReviewForm.js, frontend/src/main/components/MenuItemReviews/ReviewTable.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/pages/MenuItemReviews/MenuItemReviewCreatePage.js, frontend/src/main/pages/MenuItemReviews/MenuItemReviewEditPage.js, frontend/src/main/pages/MenuItemReviews/MenuItemReviewIndexPage.js, frontend/src/main/utils/reviewUtils.js, frontend/src/stories/components/MenuItemReviews/ReviewForm.stories.js, frontend/src/stories/components/MenuItemReviews/ReviewTable.stories.js, frontend/src/stories/pages/MenuItemReviews/MenuItemReviewCreatePage.stories.js, frontend/src/stories/pages/MenuItemReviews/MenuItemReviewIndexPage.stories.js, frontend/src/tests/components/MenuItemReviews/ReviewForm.test.js, frontend/src/tests/components/MenuItemReviews/ReviewTable.test.js, frontend/src/tests/pages/MenuItemReviews/MenuItemReviewCreatePage.test.js, frontend/src/tests/pages/MenuItemReviews/MenuItemReviewEditPage.test.js, frontend/src/tests/pages/MenuItemReviews/MenuItemReviewIndexPage.test.js, frontend/src/tests/utils/reviewUtils.test.js, src/main/java/edu/ucsb/cs156/example/controllers/MenuItemReviewsController.java, src/main/java/edu/ucsb/cs156/example/entities/MenuItemReview.java, src/main/java/edu/ucsb/cs156/example/repositories/MenuItemReviewRepository.java, src/main/resources/db/migration/changes/MenuItemReviews.json, src/test/java/edu/ucsb/cs156/example/controllers/MenuItemReviewsControllerTests.java
closes #41 
Created the new index page for reviews, tests for the index page, and a story to test the frontend.
https://6811b5ebd2e9f3288ae27ed4-mowqwpnnhz.chromatic.com/?path=/story/pages-menuitemreviews-menuitemreviewindexpage--three-items-admin-user
=> Mh review index page

frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/fixtures/reviewFixtures.js, frontend/src/main/components/MenuItemReviews/ReviewForm.js, frontend/src/main/components/MenuItemReviews/ReviewTable.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/pages/MenuItemReviews/MenuItemReviewCreatePage.js, frontend/src/main/pages/MenuItemReviews/MenuItemReviewEditPage.js, frontend/src/main/pages/MenuItemReviews/MenuItemReviewIndexPage.js, frontend/src/main/utils/reviewUtils.js, frontend/src/stories/components/MenuItemReviews/ReviewForm.stories.js, frontend/src/stories/components/MenuItemReviews/ReviewTable.stories.js, frontend/src/stories/pages/MenuItemReviews/MenuItemReviewCreatePage.stories.js, frontend/src/stories/pages/MenuItemReviews/MenuItemReviewIndexPage.stories.js, frontend/src/stories/pages/MenuItemReviews/MenuItemReviewsEditPage.stories.js, frontend/src/tests/components/MenuItemReviews/ReviewForm.test.js, frontend/src/tests/components/MenuItemReviews/ReviewTable.test.js, frontend/src/tests/pages/MenuItemReviews/MenuItemReviewCreatePage.test.js, frontend/src/tests/pages/MenuItemReviews/MenuItemReviewEditPage.test.js, frontend/src/tests/pages/MenuItemReviews/MenuItemReviewIndexPage.test.js, frontend/src/tests/utils/reviewUtils.test.js, src/main/java/edu/ucsb/cs156/example/controllers/MenuItemReviewsController.java, src/main/java/edu/ucsb/cs156/example/entities/MenuItemReview.java, src/main/java/edu/ucsb/cs156/example/repositories/MenuItemReviewRepository.java, src/main/resources/db/migration/changes/MenuItemReviews.json, src/test/java/edu/ucsb/cs156/example/controllers/MenuItemReviewsControllerTests.java
closes #42
Finished the edit page for reviews. Included tests as well as a story.
https://6811b5ebd2e9f3288ae27ed4-umqwoetegv.chromatic.com/?path=/story/pages-menuitemreviews-menuitemrevieweditpage--default
=> Mh review edit page

README.md
=> Update README.md title and links

frontend/src/App.js, frontend/src/main/components/RecommendationRequests/RecommendationTable.js, frontend/src/tests/components/RecommendationRequests/RecommendationTable.test.js
Fixed formatting for the done field for recommendation requests. It was showing up as blank but now it shows up as Yes for true and No for false.
=> fixed formatting for done field

.github/workflows/55-chromatic-pr.yml, .github/workflows/99-team02.yml, frontend/package.json, src/test/java/edu/ucsb/cs156/example/integration/UCSBDiningCommonsMenuItemIT.java
In this PR, we add two integration tests for UCSBDiningCommonsMenuItem.
This is part of the team03 assignment.
Closes #113
=> Ac ucsb dining commons menu item integration tests

.github/workflows/55-chromatic-pr.yml, .github/workflows/99-team02.yml, frontend/package.json, frontend/src/main/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemForm.js, frontend/src/tests/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemForm.test.js, src/test/java/edu/ucsb/cs156/example/integration/UCSBDiningCommonsMenuItemIT.java, src/test/java/edu/ucsb/cs156/example/web/UCSBDiningCommonsMenuItemWebIT.java
In this PR, we added End to End tests for UCSBDiningCommonsMenuItem.
Closes #118
=> Ac ucsb dining commons menu item e2e tests

.github/workflows/55-chromatic-pr.yml, .github/workflows/99-team02.yml, frontend/package.json, src/test/java/edu/ucsb/cs156/example/integration/UCSBOrganizationIT.java, src/test/java/edu/ucsb/cs156/example/web/UCSBOrganizationWebIT.java
Closes #111 
In this PR, I created End to End tests for UCSBOrganization.
=> Ben - Create End to End Tests for UCSBOrganization

.github/workflows/55-chromatic-pr.yml, .github/workflows/99-team02.yml, frontend/package.json, src/test/java/edu/ucsb/cs156/example/integration/HelpRequestIT.java
closes #125 
In this PR, we add two integration tests for the help requests table.
This is apart of the team03 assignment
=> Mz helprequests integration tests

.github/workflows/55-chromatic-pr.yml, .github/workflows/99-team02.yml, frontend/package.json, src/test/java/edu/ucsb/cs156/example/integration/HelpRequestIT.java, src/test/java/edu/ucsb/cs156/example/web/HelpRequestWebIT.java
closes #128 
IN this PR, we add end 2 end testing for help requests.
=> Mz helprequests e2e tests

src/test/java/edu/ucsb/cs156/example/integration/RecommendationRequestIT.java
Adds integration tests for recommendaiton request.
=> Add RecommendationRequestIT integration test

src/test/java/edu/ucsb/cs156/example/integration/RecommendationRequestIT.java, src/test/java/edu/ucsb/cs156/example/web/RecommendationRequestWebIT.java
Added 3 end to end tests for recommendation requests.
=> Mk recrequest e2e

src/test/java/edu/ucsb/cs156/example/integration/ArticlesIT.java, src/test/java/edu/ucsb/cs156/example/web/ArticleWebIT.java
=> e2e done for articles
